import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {execute,connectMCP} from '../dist/engine.js';
import {Store,inventory,exportArtifacts} from '../dist/storage.js';
import {mapEvent,safeError} from '../dist/protocol.js';
import {driver} from './fixture.mjs';
const here=path.dirname(fileURLToPath(import.meta.url));
async function setup(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'oa2-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const cwd=path.join(root,'repo');await fs.mkdir(cwd);return {type:'execute',requestId:'r1',prompt:'one',instructions:'context-canary',model:'explicit-test-model',cwd,stateRoot:path.join(root,'state'),inputs:[],artifacts:['artifacts']};}
async function run(req,signal=new AbortController().signal,chosen=driver){const frames=[];await execute(req,async f=>frames.push(f),signal,chosen);return frames;}
async function child(req){const requestFile=path.join(req.cwd,'request.json');await fs.writeFile(requestFile,JSON.stringify(req));return new Promise((resolve,reject)=>{const p=spawn(process.execPath,[path.join(here,'fixture.mjs'),requestFile],{env:{PATH:process.env.PATH,HOME:req.cwd,TMPDIR:os.tmpdir(),OPENAI_AGENTS_DISABLE_TRACING:'1'}});let out='',err='';p.stdout.on('data',b=>out+=b);p.stderr.on('data',b=>err+=b);p.on('error',reject);p.on('exit',code=>{if(code!==0)return reject(new Error(`exit ${code}: ${err}`));if(err)process.stderr.write(err);resolve(out.trim().split('\n').map(s=>JSON.parse(s)));});});}
test('real Unix sandbox: cross-process archive recovery and artifact create/modify/delete; simulated model',async t=>{
 const req=await setup(t);const a=await child(req);assert.equal(a.at(-1).status,'completed');assert.equal(await fs.readFile(path.join(req.cwd,'artifacts/result.txt'),'utf8'),'first');
 const token=a.at(-1).sessionId;const b=await child({...req,requestId:'r2',sessionId:token,prompt:'two'});assert.equal(b.at(-1).status,'completed',JSON.stringify(b));assert.equal(await fs.readFile(path.join(req.cwd,'artifacts/result.txt'),'utf8'),'second');await assert.rejects(fs.access(path.join(req.cwd,'artifacts/delete.txt')));
 const store=new Store({...req,sessionId:token});await store.open();const restored=await store.load();assert.deepEqual(restored.history.filter(x=>x.role==='user').map(x=>x.content),['one','two']);await store.close();
 const dirs=await fs.readdir(path.join(store.root,'workspaces'));assert.equal(dirs.length,0);assert.equal((await fs.stat(store.root)).mode&0o777,0o700);
 const pointer=JSON.parse(await fs.readFile(path.join(store.root,'current.json'),'utf8'));await fs.appendFile(path.join(store.root,pointer.generation,'workspace.tar'),'corrupt');const c=await run({...req,sessionId:token});assert.equal(c.at(-1).error,'CHECKPOINT_INVALID');
});
test('real SDK explicit MCP stdio list/call round trip',async t=>{const req=await setup(t);req.mcp={mcpServers:{fixture:{command:process.execPath,args:[path.join(here,'mcp-fixture.mjs')]}}};const servers=await connectMCP(req);try {assert.equal((await servers[0].listTools())[0].name,'echo');const out=await servers[0].callTool('echo',{text:'handler-canary'});assert.match(JSON.stringify(out),/handler-canary/);}finally{await Promise.all(servers.map(s=>s.close()));}});
test('required MCP failure prevents driver/model and cleans real workspace',async t=>{const req=await setup(t);req.mcp={mcpServers:{bad:{command:path.join(req.cwd,'missing')}}};let called=false;const frames=await run(req,undefined,async()=>{called=true;throw new Error();});assert.equal(called,false);assert.equal(frames.at(-1).error,'MCP_UNREADY');const root=path.join(req.stateRoot,frames.at(-1).sessionId);assert.equal((await fs.readdir(path.join(root,'workspaces'))).length,0);await fs.access(path.join(root,'recovery.tar'));assert.equal((await run({...req,sessionId:frames.at(-1).sessionId})).at(-1).error,'DIRTY_SESSION');});
test('real Unix cancellation stops shell child and retains dirty recovery',async t=>{const req=await setup(t),controller=new AbortController();let pid;const started=Date.now();const frames=await run(req,controller.signal,async(a,i,o)=>{const r=await o.sandbox.session.exec({cmd:'echo $$; exec sleep 60',login:false,yieldTimeMs:10});pid=Number(r.stdout.trim());controller.abort();throw new Error('cancel');});assert.equal(frames.at(-1).status,'aborted');assert.ok(Date.now()-started<3000,'bounded SDK root-process cleanup');assert.ok(pid>0);assert.throws(()=>process.kill(pid,0));await fs.access(path.join(req.stateRoot,frames.at(-1).sessionId,'recovery.tar'));});
test('artifact conflict and unsafe paths reject before overwrite',async t=>{const req=await setup(t);await fs.mkdir(path.join(req.cwd,'artifacts'));await fs.writeFile(path.join(req.cwd,'artifacts/a'),'old');const baseline=await inventory(req.cwd,['artifacts']);await fs.writeFile(path.join(req.cwd,'artifacts/a'),'human');await assert.rejects(exportArtifacts(req.cwd,req.cwd,['artifacts'],baseline),/ARTIFACT_CONFLICT/);await fs.symlink(req.cwd,path.join(req.cwd,'link'));await assert.rejects(inventory(req.cwd,['link']),/UNSAFE_PATH/);await assert.rejects(inventory(req.cwd,['../escape']),/UNSAFE_PATH/);});
test('events retain call identity and errors never echo raw credentials',()=>{assert.deepEqual(mapEvent({type:'run_item_stream_event',name:'tool_output',item:{rawItem:{callId:'c1'},output:'done'}}),{kind:'tool_result',id:'c1',name:'sandbox',text:'done'});assert.equal(safeError(new Error('sensitive-token-canary')),'SDK_FAILURE');assert.equal(mapEvent({type:'run_item_stream_event',name:'message_output_created'}),undefined);});
